languageCode = "en-gb"
#
# For private development of the site, use development webserver
baseURL = "http://10.10.11.111/"
title = "DEVELOPMENT rollyourown.xyz"
#
# For production, use production webserver
#baseURL = "https://rollyourown.xyz/"
#title = "rollyourown.xyz"
#
theme = "rollyourown-theme"
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"

[params]
  authorName = "xyzroller"
  description = ""
  dateFormat = "Jan 2, 2006"
  homeText = "Coming soon"
  
[permalinks]
  project = "/:sections/:filename/"

[taxonomies]
  tag = "tags"
    
# See https://feathericons.com/
# The value of pre is the icon name
[languages]
  
  [languages.en]
    weight = 1
    [[languages.en.menu.main]]
      name = "Home"
      pre = "home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Rollyourown..."
      pre = "code"
      url = "/rollyourown/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Collaborate"
      pre = "git-pull-request"
      url = "/collaborate/"
      weight = 3
    [[languages.en.menu.main]]
      name = "About"
      pre = "grid"
      url = "/about/"
      weight = 4

  [languages.de]
    weight = 2
    [[languages.de.menu.main]]
      name = "Start"
      pre = "home"
      url = "/de/"
      weight = 1
    [[languages.de.menu.main]]
      name = "Rollyourown..."
      pre = "code"
      url = "/de/rollyourown/"
      weight = 2
    [[languages.de.menu.main]]
      name = "Mitwirken"
      pre = "git-pull-request"
      url = "/de/collaborate/"
      weight = 3
    [[languages.de.menu.main]]
      name = "Über"
      pre = "grid"
      url = "/de/about/"
      weight = 4
