baseURL = "https://rollyourown.xyz/"
languageCode = "en-us"
title = "rollyourown.xyz"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Coming soon"
  
[permalinks]
  project = "/:sections/:filename/"

[taxonomies]
  tag = "tags"
    
# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "home"
    pre = "home"
    url = "/"
    weight = 1
#  [[menu.main]]
#    name = "rollyourown..."
#    #pre = "folder"
#    #pre = "chevrons-down"
#    pre = "code"
#    url = "/rollyourown/"
#    weight = 2
#  [[menu.main]]
#    name = "collaborate"
#    #pre = "code"
#    pre = "git-pull-request"
#    #pre = "users"
#    url = "/collaborate/"
#    weight = 3
#  [[menu.main]]
#    name = "credits"
#    pre = "heart"
#    #pre = "smile"
#    #pre = "star"
#    #pre = "thumbs-up"
#    url = "/credits/"
#    weight = 4
#  [[menu.main]]
#    name = "contact"
#    #pre = "at-sign"
#    pre = "mail"
#    url = "/contact/"
#    weight = 5
